### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.GenericSetup#126]
### What I did:

I looked at the test runs in GHA.
e. g. https://github.com/zopefoundation/Products.GenericSetup/actions/runs/4274869009/jobs/7441795588

### What I expect to happen:

Green tests.

### What actually happened:

Tests are broken probably due to changes in newer setuptools versions resp. its bundled `packaging` module.

### What version of Python and Zope/Addons I am using:

* Zope 5
* Python >= 3.7

Cc-ing some contributors:

@dataflake @mauritsvanrees

**Comment by mauritsvanrees** [comment]
That is due to `setuptools` 66 that no longer accepts legacy versions.
We could treat all such versions as 0.0.0.  Or easier: 0.
I am trying a PR.

**Comment by mauritsvanrees** [comment]
Or treat it as `0+<bad version>`.  See [local version segments](https://peps.python.org/pep-0440/#local-version-segments) in pep 440.  Then we still get some sort order.
