### ISSUE TITLE
TarballImportContext crashes when comparing the last char of empty strings

### ISSUE THREAD

**Issue by tobiasherp** [zopefoundation/Products.GenericSetup#14]
Products.GenericSetup, v1.7.6:

In Products/GenericSetup/context.py, there are two comparisons of path[-1] to ‘/’, which must fail for empty strings. IMO, here the endswith method must be used.

The empty string seems to be a known special case for tarballs.

See pull request #13; this ticket is identical with https://bugs.launchpad.net/zope2/+bug/1479268.

**Comment by mauritsvanrees** [comment]
The fix looks good. Thanks. I have merged it.
