### ISSUE TITLE
Not list upgradeSteps if the profile isn't installed

### ISSUE THREAD

**Issue by idgserpro** [zopefoundation/Products.GenericSetup#25]
We had problems runing a upgradeStep of profile not installed. See:

https://github.com/simplesconsultoria/sc.embedder/issues/38

upgradeStep like [this](https://github.com/collective/collective.oembed/blob/master/collective/oembed/upgrades.zcml#L7), are listed even if the profile isn't installed. Is it really necessary list upgradeSteps  of profiles not installed?

**Comment by mauritsvanrees** [comment]
This was fixed a few days ago with pull request #23 :-)
@tseaver @esteele a release would be welcome.

**Comment by mauritsvanrees** [comment]
Or grant me PyPI access. ID: maurits.
