### ISSUE TITLE
New release? 1.8.3

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.GenericSetup#28]
Any chance of a new release? I would like to use the `toolset.xml` improvements from my merged pull request #26.

Release rights on PyPI for user `maurits` would also be gladly accepted. :-)

**Comment by tseaver** [comment]
I've added you as a 'Maintainer' on PyPI:  "You may fire when you are ready, Gridley!".

**Comment by mauritsvanrees** [comment]
Thanks. I have release 1.8.3.
You've got me reading up on U.S. naval history. :-)

**Comment by tseaver** [comment]
That quote is supposed to be from the Battle of Manila Bay (1898). At the other end of Ridley's career was the Battle of Mobile Bay (1864), the source of another famous naval quote:  "Damn the torpedoes, full speed ahead!"
