### ISSUE TITLE
Why don't we pass the ImportContext to pre_handler and post_handler?

### ISSUE THREAD

**Issue by pbauer** [zopefoundation/Products.GenericSetup#29]
If I understand it correctly the main thing about `pre_handler` and `post_handler` is to replace the cumbersome registration of import-steps. Import-steps were not passed the GenericSetup-Tool but the `Products.GenericSetup.context.DirectoryImportContext` which has the nice helper `_profile_path` and `readDataFile` which allowed to read various files (e.g. a csv-file with data from which to create users or content). Now have to do this by hand which makes switching existing code from import-steps to post_handlers a little more work than would be nice. 
I just want to ask if there is any special reason why we don't pass `context` in `Products.GenericSetup.tool.SetupTool._runImportStepsFromContext` to `_doRunHandler` and then pass that to the handler.

**Comment by mauritsvanrees** [comment]
It seemed more useful to me in most use cases to pass a 'normal' context. `portal_setup` as context makes them more like upgrade steps, who get this same context.

If you need `readDataFile` or `_profile_path` you are probably better off keeping the good old import steps: they have not gone away.

**Comment by mauritsvanrees** [comment]
The handler is for one specific profile, so you know the profile id. Then it looks like this is the code that is needed to get the old context:

```
good_old_context = context._getImportContext(profile_id)
```

**Comment by pbauer** [comment]
That's exactly what I did for quaive. I was just wondering. I'm ok with keeping it as it is now.
