### ISSUE TITLE
Replace zope.formlib with z3c.form

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/Products.GenericSetup#31]
Should that be something desirable? Plone 5 already made a strong move out of zope.formlib in favor of z3c.form and one of the only few packages that do still depend on it is Products.GenericSetup: https://github.com/zopefoundation/Products.GenericSetup/search?utf8=%E2%9C%93&q=formlib

**Comment by tseaver** [comment]
I would be glad to review a PR switching them out.  Only one view, `ComponentsSetupView` is affected.

**Comment by mauritsvanrees** [comment]
Solved by #34
