### ISSUE TITLE
Online docs are outdated

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.GenericSetup#39]
The [GenericSetup PyPI page](https://pypi.python.org/pypi/Products.GenericSetup) points to documentation at http://packages.python.org/Products.GenericSetup/ and https://pythonhosted.org/Products.GenericSetup/. The first url redirects to the second one.

What we see there, is documentation for version 1.7.0. Does anyone know how to update this?

Alternatively, we could rearrange things and move to readthedocs.

**Comment by tseaver** [comment]
I'm all in favor of moving them to RTD.  I think we would need to create a one-file tarball with a link to the RTD site for upload into the PyPI -> pythonhosted form.

**Comment by icemac** [comment]
See https://blog.gocept.com/2017/05/27/move-documentation-from-pythonhosted-org-to-readthedocs-io/ for an example of what @tseaver suggested.

**Comment by icemac** [comment]
I created http://productsgenericsetup.readthedocs.io and added @tseaver as developer.

**Comment by icemac** [comment]
Anyone else who needs/wants to administer this package at RTD?

**Comment by mauritsvanrees** [comment]
Can you add me? My RTD account is [maurits](https://readthedocs.org/profiles/maurits/). ( I haven't really done anything with that account, to be honest.)

**Comment by icemac** [comment]
@mauritsvanrees I added you as developer on RTD for this package. Could you give me PyPI rights in exchange so I can add the redirect from pythonhosted to RTD. My PyPI account name is `icemac`.

**Comment by mauritsvanrees** [comment]
Thank you.
I somehow cannot give you PyPI rights. I can login, and see all admin options for the package, but when I click on Roles, I get a basic auth popup where my PyPI account does not work. Strange. And on pypi.org I do not see any options for editing packages manually yet.

**Comment by mauritsvanrees** [comment]
Ah, I am only *maintainer* on PyPI, not owner, so I cannot give a role to others. @tseaver, @dataflake and @esteele can do that.

**Comment by tseaver** [comment]
I just added `icemac` as an Owner on PyPI.

**Comment by icemac** [comment]
@mauritsvanrees Sorry for bothering you. I looked only at the new [PyPI](https://pypi.org/project/Products.GenericSetup/) which no longer distinguishes between owners and maintainers at display.

**Comment by icemac** [comment]
The redirect has still to be done.

**Comment by icemac** [comment]
But the redirect cannot be done until pypa/warehouse#582 is fixed.

There are two options:

1.  delete the documentation at http://pythonhosted.org/Products.GenericSetup/ and live with the broken link at the PyPI page until a release is made and for older releases forever. (But I cannot say if it is still possible to delete this documentation as I did not try it.)
2. wait for pypa/warehouse#582 to be fixed

Suggestions?

**Comment by icemac** [comment]
@mauritsvanrees 👍

**Comment by icemac** [comment]
I'm going to cut a release in the next days so the PyPI page will point to the documentation on RTD.

**Comment by icemac** [comment]
I just released 1.10.0 to PyPI, see https://pypi.org/project/Products.GenericSetup/

**Comment by mauritsvanrees** [comment]
Deleting the pythonhosted documentation is now apparently possible from within pypi.org (I don't have enough rights). But perhaps we should wait till we can turn it into a redirect. See https://github.com/pypa/warehouse/issues/3417

**Comment by dataflake** [comment]
The good: In fe1292f808cdad8df6a3701fdf2ddc30513fbc12 I added additional links that will show up in the "Project links" section on the PyPI page **if ``twine`` is used to upload the package to PyPI, ``python setup.py ... upload``  seems to disregard ``project_urls``  in ``setup.py``**.

The bad: I had not read all the way to the bottom of this issue and deleted the outdated documentation. I didn't realize this wasn't planned yet.😞

**Comment by icemac** [comment]
@dataflake No problem. This way at least this issue can get closed. 😀
