### ISSUE TITLE
 GenericSetup has problems with BrowserLayers

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/Products.GenericSetup#6]
In https://bugs.launchpad.net/zope-cmf/+bug/530943, @do3cc  reported:

> When trying to modfiy the peristent registry with the manage_components tab, it usually fails if browserlayers are registered as utilities.
> 
> The code tries to generate a xml configuration for the utility and assumes type(utility) as the factory for the BrowserLayers. The BrowserLayer utility is an interface, type resorts to zope.interface.interface.InterfaceClass. This cannot be called without arguments. Thus when loading the new utilities, it fails for Browserlayers.

and attached a patch for a testcase to reproduce the issue:

https://bugs.launchpad.net/zope-cmf/+bug/530943/+attachment/1173798/+files/patch

with the comment:

> Here is a traceback:

``` python
  Module plone.postpublicationhook.hook, line 74, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module zope.formlib.form, line 769, in __call__
  Module Products.Five.formlib.formbase, line 55, in update
  Module zope.formlib.form, line 750, in update
  Module zope.formlib.form, line 594, in success
  Module Products.Five.formlib.formbase, line 69, in handle_edit_action
  Module zope.formlib.form, line 528, in applyChanges
  Module zope.schema._bootstrapfields, line 183, in set
  Module Products.GenericSetup.browser.components, line 55, in _setBody
  Module Products.GenericSetup.utils, line 544, in _importBody
  Module Products.GenericSetup.components, line 76, in _importNode
  Module Products.GenericSetup.components, line 173, in _initUtilities
TypeError: __init__() takes at least 2 arguments (1 given)
```

> This code is version 1.4.5
> 
> I have written a test for it.
> 
> I am not sure what a clean way of fixing would be. It seems to me that the code tries to create its own xml serialization and fails. I am not sure whether having your own serialisation here makes sense.

Later @do3cc wrote:

> I talked with hannosch about the issue.  In the end, the view never really worked in all cases, but some objected to the removal.
> 
> Since it is easily feasable to get a list of all utilities and adapters, but not so easy to serialize and deserialize them, a potential fix would be to create a new simple ui that lists local adapters and utilities and offers a delete action for each.

Yvo Schubbe responded:

> Thanks for the report! AFAICS this issue is not specific to the manage_components tab, your testcase is for the ComponentRegistryXMLAdapter that is primarily used for importing and exporting GenericSetup profiles.
> 
> ComponentRegistryXMLAdapter has its limitations and a real UI for five.localsitemanager site managers would be better than the current view, but that's a completely different issue.
> 
> Your testcase just shows that imports using InterfaceClass as factory don't work, but that's not really the problem. The real issue seems to be the export/serialization. And if you report issues with the ComponentRegistryXMLAdapter please report them against version 1.5+ because it has many components handler fixes 1.4.5 does not contain.

@flipmcf followed up:

> sorry to raise the dead here, but I'm seeing this behavior also with an 3rd party add-on which will go unnamed.
> 
> I _may_ have a workaround, but it's unconfirmed:
> 
> I think a browserlayer.xml like this will create the utility which exports in componentregistry with the bad factory:

``` xml
 <?xml version="1.0"?>
 <layers>
    <layer name="MyLayer"
      interface="IMyLayer"/>
 </layers>
```

But a browserlayer.xml like this:

``` xml
 <?xml version="1.0"?>
 <layers name="MyLayers" meta_type="ComponentRegistry">
    <layer name="MyLayer"
      interface="IMyLayer"/>
 </layers>
```

> Seems to avoid the issue and doesn't muck about with componentregistry's export process.
> 
> Would love to get a confirmation of this from someone, and an official "Nod of the head" that the 2nd example of a browserlayer.xml generic setup profile is the "Correct" way to do it.

@flipmcf later wrote:

> Please disregard previous message. I experimented and saw no difference.

and then again:

> I would like to raise the severity of this issue as it seems related to causing zope to spin in some situations.  Our site administration workflow depends on versioned, up-to-date GenericSetup configuration profiles and running import steps from the ZMI when production changes occur.  We have too many production instances to point-and-click our way through the ZMI for each change that deploys to production.
> 
> Zope2-2.13.8-py2.7
> zope.component-3.9.5-py2.7
> Products.CMFCore-2.2.4-py2.7
> 
> To reproduce, I would use the package 'quintagroup.plonegooglesitemaps' which registers a browser layer upon installation.
> 
> Install this product (it's quite easy) and configure a news-sitemap.xml
> 
> Request the news-sitemap.xml through a browser request, and note it works just fine - you get some xml - empty is ok.
> 1. Export local compoent registry (componentregistry.xml) and re-import it: This aggrivates the bug that Patric Gerken describes.  Essentially at this point, you cannot save and version your ZMI settings (like we do) because imports will not work anymore.
> 2. Next: Comment out the offending utility in componentregistry.xml and import again. Of course, now it will work.
> 3. Access the news-sitemap.xml you created above.  Zope will spin at %100 cpu and can only be fixed through a hard restart of the instance.
> 4. Fix by running the browserlayer import step (return to step 1)
> 
> I have a few traceback / dumps from my spinning zope process that I can provide upon request.

**Comment by flipmcf** [comment]
Thanks for opening on Github Tres.

I spoke briefly with folks at the Plone booth about this at Pycon 2015 and they seemed to believe that the answer was "Don't import component registry, ever".   Nice pragmatic approach, but doesn't sit well with me.

**Comment by do3cc** [comment]
The spinning issue you mentioned is probably a different problem which might have a simpler fix.
For the problem with GS profiles and components, I fear there is nobody with time and the knowledge to fix this quickly. I doubt I know enough to fix it within two hours and I don't have much more spare time for this kind of things.
What I can provide here and by mail is answers to specific questions in case you want to fix it yourself.

**Comment by jensens** [comment]
Btw., this is still broken, i.e. in any Plone 5.2:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module Products.GenericSetup.browser.components, line 80, in __call__
  Module Products.GenericSetup.browser.components, line 76, in update
  Module Products.GenericSetup.browser.components, line 55, in _setBody
  Module Products.GenericSetup.utils, line 523, in _importBody
  Module Products.GenericSetup.components, line 104, in _importNode
  Module Products.GenericSetup.components, line 349, in _initUtilities
TypeError: __init__() missing 1 required positional argument: 'name'

```

**Comment by jensens** [comment]
Anyway, this is still broken. We just stumbled over this one at Beethoven Sprint in Bonn today.
