### ISSUE TITLE
Fix Flake8 errors and deprecation warnings

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.GenericSetup#63]
There are many deprecation warnings issued by the tests and the flake8 check (`tox -eflake8`) complains about many violations.

It would be nice to get them fixed. (Flake 8 could even be tested on Travis CI to ensure Flake8 compatibility for the future.)

**Comment by dataflake** [comment]
Flake8 is green and there's just a few DeprecationWarnings under Python 3 that don't warrant the effort to hun them all down.
