### ISSUE TITLE
[py3] Permissions are imported as bytes but expected to be strings

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/Products.GenericSetup#71]
I was having a look at why some robot tests are failing on Plone 5.2 running on python 3.6 and noticed that the Plone controlpanel to manage actions was failing due to a permission missing.

On closer inspection, the ZMI seems to be also broken as there is no permission set on a given action.

Turns out though, that the permission is imported from ``actions.xml`` but stored on the action object as ``(b'View',)`` but when compared with the list of available permissions, none of them matches because that list is a list of strings rather than bytes.

Which one should prevail? Available permissions should be also bytes or rather permissions should be imported as strings? :thinking:

**Comment by davisagli** [comment]
Zope appears to treat permissions as native strings (str as bytes in Python 2 and str as text in Python 3)

**Comment by davisagli** [comment]
I attempted a workaround here: https://github.com/zopefoundation/Products.GenericSetup/commit/388abb091ec630bab5cecd00366fc14b2879c514

**Comment by dataflake** [comment]
@gforcada Seeing how the workaround had been applied, can this be closed?

**Comment by icemac** [comment]
There was no reaction in a month, so closing the issue.

Feel free to reopen it if you have new details,
