### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.GenericSetup#76]
```python
Products/GenericSetup/components.py:26: DeprecationWarning: IComponentRegistry is deprecated. Import from zope.interface.interfaces
Products/GenericSetup/utils.py:365: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
Products/GenericSetup/utils.py:373: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
```

**Comment by jugmac00** [comment]
Warning two and three are understandable to me.

But I do not get the first warning. When I look up components.py line 26, it reads:
from zope.interface.interfaces import IComponentRegistry

In zope.interface interfaces there is the class IComponentRegistry.

Maybe someone can give me a hint
- how and when the warning is generated
- why the warning is generated
- and what to do about it?

I have to admit I lack both knowledge with the interface topic and with deprecations.

**Comment by jamadden** [comment]
You need zope.component 4.5.0+ [to see the warnings](https://github.com/zopefoundation/zope.component/commit/741972ee209a9a6dad7696a1ac8e02c0d2e7bcdc).

**Comment by jugmac00** [comment]
@jamadden Thank you!

Changing cgi.escape to html.escape will change the behaviour of _Element.writexml as cgi.escape, which gets called with quote=True will only quote double quotes, whereas html.escape with quote=True will quote both single and double quotes.

Thoughts:
So, either there will be more escaping which could cause trouble with a consument, or there will be less escaping, which could be a security issue.

Also, escape is used twice in the writexml method - once with quote=True, once with quote=False(implicit behaviour of cgi.escape) - is there a reason for that?

**Comment by icemac** [comment]
@jugmac00 I got these deprecation warnings when running the tests for `Products.CMFCore` using the latest release of GenericSetup.

**Comment by jugmac00** [comment]
@icemac Thank you! Figured it out!

@icemac @jamadden @dataflake 
As mentioned in https://github.com/zopefoundation/Products.GenericSetup/issues/76#issuecomment-436385972 cgi.escape and html.escape work differently, ie html.escapce also escapes single quotes.

I do not dare to make these changes and possibly break some consumer of this Product. Somebody else should look into this issue.

**Comment by dataflake** [comment]
Take a look at #78 

The differences in XML representation coming out of the export do not matter at all. The only important factor is whether all XML representations import cleanly and give the expected result. I believe the tests in #78 prove that conclusively.
