### ISSUE TITLE
Unicode/Text support for writeDataFile: ValueError: Unicode text is not supported, even if it only contains ascii. Please encode your data. See GS 1.7.0 changes for more

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Products.GenericSetup#79]
See

https://github.com/plone/Products.CMFPlone/issues/2784

I don't see why we need to raise an explicit error instead of converting to utf-8 if needed under the hood?

https://github.com/zopefoundation/Products.GenericSetup/blob/master/Products/GenericSetup/context.py#L441-L444

**Comment by icemac** [comment]
@dataflake Do you have an idea, how to fix this issue?

**Comment by dataflake** [comment]
@zopyx @icemac not a clue. That code is over 7 years old. Andreas is absolutely right, the error is useless. At least an attempt should be made to encode it. Not sure if hardcoded UTF-8 or the value of `ZPublisher.HTTPRequest.default_encoding` would be a better choice. But then again I think GS hardcodes UTF-8 all over the place.
