### ISSUE TITLE
Python 3: showing old upgrades throws an exception

### ISSUE THREAD

**Issue by batlock666** [zopefoundation/Products.GenericSetup#81]
I have a package with two upgrade steps. For each upgrade step source = 1, destination = 1, and sortkey = 1. When I try to list the old upgrades, I get the following exception:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 142, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 295, in publish_module
  Module ZPublisher.WSGIPublisher, line 229, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module Shared.DC.Scripts.Bindings, line 330, in __call__
  Module Shared.DC.Scripts.Bindings, line 367, in _bindAndExec
  Module Products.PageTemplates.PageTemplateFile, line 141, in _exec
  Module Products.PageTemplates.PageTemplate, line 83, in pt_render
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 90, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.utils, line 75, in raise_with_traceback
  Module chameleon.template, line 187, in render
  Module 561e1882708296964a293b8943c621a1.py, line 685, in render
  Module Products.GenericSetup.tool, line 1002, in listUpgrades
  Module Products.GenericSetup.upgrade, line 270, in listUpgradeSteps
TypeError: '<' not supported between instances of 'dict' and 'dict'

 - Expression: " python:context.listUpgrades(profile_id, show_old=show_old"
 - Filename:   manage_upgrades
 - Location:   (line 69: col 27)
 - Arguments:  template: <ImplicitAcquisitionWrapper manage_upgrades at 0x7f7c13b013a8>
               here: <ImplicitAcquisitionWrapper portal_setup at 0x7f7c13b01090>
               context: <ImplicitAcquisitionWrapper portal_setup at 0x7f7c13b01090>
               container: <ImplicitAcquisitionWrapper portal_setup at 0x7f7c13b01090>
               nothing: <NoneType - at 0xa02bc0>
               options: {...} (1)
               root: <ImplicitAcquisitionWrapper  at 0x7f7c12cb4948>
               request: <WSGIRequest - at 0x7f7c0e1c3780>
               modules: <_SecureModuleImporter - at 0x7f7c21f42630>
               user: <ImplicitAcquisitionWrapper - at 0x7f7c13b01a20>
               default: <object - at 0x7f7c248ecac0>
               repeat: {...} (0)
               loop: {...} (1)
               wrapped_repeat: <SafeMapping - at 0x7f7c122d7b88>
               target_language: <NoneType - at 0xa02bc0>
               translate: <function translate at 0x7f7c0dac7ea0>
               profile_id: ugent.editmode:default
               prof_with_upgrades: <list - at 0x7f7c12b67988>
               prof_with_pending_upgrades: <list - at 0x7f7c12086bc8>
               prof_uptodate: <list - at 0x7f7c133bf848>
               has_pending_upgrades: False
               show_old: 1

I get this problem with Python 3, but not with Python 2. It looks like the method listUpgradeSteps tries to sort a list of upgrade steps by comparing dicts, which works in Python 2, but not in Python 3.

**Comment by dataflake** [comment]
Fixed by #82
