### ISSUE TITLE
Update to adapt to Zope 5 deprecations

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Products.GenericSetup#90]
https://github.com/zopefoundation/Products.GenericSetup/blob/88f9289bf90e7b7e5d30d4b7d8d62d8beb8f4684/Products/GenericSetup/browser/components.py#L17

This line is causing my watchdog staging environment to fail, because the referenced file was removed at <https://github.com/zopefoundation/Zope/commit/f15d25c4a3b307795994904f792b6a4a3243d44d>

Not sure how to best deal with this, maybe have an alternative ready and fall back to that if the module isn't there anymore with a comment / deprecation to to remove the fallback after zope 5 is released?

**Comment by icemac** [comment]
Since https://github.com/zopefoundation/Zope/commit/92047edfc12fa38eb281cfd42419d0cb90490b7d `processInputs` is done automatically for views implementing `IBrowserPage`. Maybe the view using `processInputs` here can be made implementing `IBrowserPage` so the separate call to `processInputs` can hopefully be avoided.

A PR is welcome.

**Comment by icemac** [comment]
Hm, actually it is `postProcessInputs` but it is not called in the WSGIPublisher.

**Comment by dwt** [comment]
Sorry, I don't follow - does this mean that adapting. iBrowserPage would not be sufficient?

**Comment by icemac** [comment]
No, implementing would be the key but not for the WSGIPublisher: it does not include the code added in https://github.com/zopefoundation/Zope/commit/92047edfc12fa38eb281cfd42419d0cb90490b7d to `Publish.py`. I currently do not know where WSGIPublisher does the decoding.

**Comment by dwt** [comment]
@dataflake  Does your commit https://github.com/zopefoundation/Products.GenericSetup/commit/89d8559ac298cab2d6b04446c5e70370d2e5c2d4 solve this issue? (Sorry, I didn't follow this issue too much)

**Comment by dataflake** [comment]
No it does not. Sorry, I am not subscribed to this repo because I don't use GS myself.

**Comment by dataflake** [comment]
By the way, Zope 4 does have a deprecation warning that the function will go away in Zope 5.

**Comment by icemac** [comment]
`ZPublisher.HTTPRequest.HTTPRequest.processInputs` does the decoding via `FieldStorage`, see https://github.com/zopefoundation/Zope/blob/655b0aed4dd1fc159e3b5fc10c882e5b96c77a1d/src/ZPublisher/HTTPRequest.py#L487-L490

I think this means that even `postProcessInputs` is no longer needed.

**Comment by icemac** [comment]
I created zopefoundation/Zope#782 to track the removal of `postProcessInputs`.

**Comment by icemac** [comment]
@dataflake wrote:
> No it does not. Sorry, I am not subscribed to this repo because I don't use GS myself.

I think 89d8559 should solve the issue because since this commit `Products.Five.browser.decode.processInputs` is no longer used.

**Comment by dataflake** [comment]
@icemac I had totally forgotten about it, yes, 89d8559 should solve it.

@dwt I released version 2.0.2 at the time I added that fix. Have you tried that?

**Comment by dwt** [comment]
@dataflake Not yet @drfho  wanted to take a look at this. Pinging him now...

**Comment by drfho** [comment]
@dataflake 
With change https://github.com/zopefoundation/Products.GenericSetup/commit/89d8559ac298cab2d6b04446c5e70370d2e5c2d4 it works perfect, many thanks!

**Comment by icemac** [comment]
@drfho Nice to hear, so I am going to close this issue.
